theme: jekyll-theme-cayman
title: CVPR 2021 Workshop on Event-based Vision
github: 
  is_project_page: false

twitter:
  username: guillermogb
  
# About/contact
author:
  name:       Guillermo Gallego
  url:        http://www.guillermogallego.es
  
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/cvpr2021_eventvision_workshop.jpg
        height: 630
        width: 1200
